### ISSUE TITLE
maint branches

### ISSUE THREAD

**Issue by srl295** [unicode-org/icu-git#2]
I should have been able to get "maint-56" etc, as a branch, mapping something such as `/branches/maint/maint-*` to `refs/heads/maint-*`

**Comment by jefgen** [comment]
Running the scripts with the updated munged svndump and subgit.config I see the `maint` branches now, so I think this issue can be resolved. 👍 

    maint/maint-50
    maint/maint-51
    maint/maint-52
    maint/maint-53
    maint/maint-54
    maint/maint-55
    maint/maint-56
    maint/maint-57
    maint/maint-58
    maint/maint-59
    maint/maint-60
    maint/maint-61
    maint/maint-62
