### ISSUE TITLE
old history

### ISSUE THREAD

**Issue by srl295** [unicode-org/icu-git#3]
Current subgit approach doesn't include old-C and old-J.

Ideas:

- do nothing. Let the past be the past. Dig it out of svn if you need it.
- somehow convert the C, and the J, repos separately, and glue them together, rebasing the 'new' repo on top. 
- map `/icu/trunk` and `/icu4j/trunk` into `refs/heads/icu4c-old` and `refs/heads/icu4j-old` - ugly, but could be the simplest option (besides doing nothing, that is)
- include `trunk=` directives twice?  
- custom code

**Comment by jefgen** [comment]
I think this is obsolete now, as @srl295 came up with the ingenious idea to edit the SVNdump.

> Idea: create a modified svn history as if /icu4j and /icu4c are parallel
> modify svn dump format (could munge the commit logs, etc.) 

See the scripts here for more:  https://github.com/unicode-org/icu-remunge-svndump/

**Comment by srl295** [comment]
☝️
